/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2022 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "neu_json_login.h"

/**
 * @brief 从JSON字符串解码登录请求
 *
 * @param buf 包含JSON数据的字符串
 * @param result 解码结果存储位置，由函数分配内存
 * @return int 成功返回0，失败返回-1
 */
int neu_json_decode_login_req(char *buf, neu_json_login_req_t **result)
{
    int ret = 0;

    neu_json_login_req_t *req         = calloc(1, sizeof(neu_json_login_req_t));
    neu_json_elem_t       req_elems[] = { {
                                        .name = "pass",
                                        .t    = NEU_JSON_STR,
                                    },
                                    {
                                        .name = "name",
                                        .t    = NEU_JSON_STR,
                                    } };
    ret = neu_json_decode(buf, NEU_JSON_ELEM_SIZE(req_elems), req_elems);
    if (ret != 0) {
        goto decode_fail;
    }

    req->pass = req_elems[0].v.val_str;
    req->name = req_elems[1].v.val_str;

    *result = req;
    return ret;

decode_fail:
    free(req);
    return -1;
}

/**
 * @brief 释放登录请求资源
 *
 * @param req 要释放的请求结构体指针
 */
void neu_json_decode_login_req_free(neu_json_login_req_t *req)
{

    free(req->pass);
    free(req->name);

    free(req);
}

/**
 * @brief 从JSON字符串解码密码修改请求
 *
 * @param buf 包含JSON数据的字符串
 * @param result 解码结果存储位置，由函数分配内存
 * @return int 成功返回0，失败返回-1
 */
int neu_json_decode_password_req(char *buf, neu_json_password_req_t **result)
{
    int ret = 0;

    neu_json_password_req_t *req = calloc(1, sizeof(neu_json_password_req_t));
    neu_json_elem_t          req_elems[] = {
        {
            .name = "name",
            .t    = NEU_JSON_STR,
        },
        {
            .name = "old_pass",
            .t    = NEU_JSON_STR,
        },
        {
            .name = "new_pass",
            .t    = NEU_JSON_STR,
        },
    };
    ret = neu_json_decode(buf, NEU_JSON_ELEM_SIZE(req_elems), req_elems);
    if (ret != 0) {
        goto decode_fail;
    }

    req->name     = req_elems[0].v.val_str;
    req->old_pass = req_elems[1].v.val_str;
    req->new_pass = req_elems[2].v.val_str;

    *result = req;
    return ret;

decode_fail:
    free(req);
    return -1;
}

/**
 * @brief 释放密码修改请求资源
 *
 * @param req 要释放的请求结构体指针
 */
void neu_json_decode_password_req_free(neu_json_password_req_t *req)
{
    if (req) {
        free(req->name);
        free(req->old_pass);
        free(req->new_pass);

        free(req);
    }
}

/**
 * @brief 编码登录响应为JSON
 *
 * @param json_object 输出的JSON对象
 * @param param 要编码的响应结构体指针(neu_json_login_resp_t类型)
 * @return int 成功返回0，失败返回非0
 */
int neu_json_encode_login_resp(void *json_object, void *param)
{
    int                    ret  = 0;
    neu_json_login_resp_t *resp = (neu_json_login_resp_t *) param;

    neu_json_elem_t resp_elems[] = { {
        .name      = "token",
        .t         = NEU_JSON_STR,
        .v.val_str = resp->token,
    } };
    ret = neu_json_encode_field(json_object, resp_elems,
                                NEU_JSON_ELEM_SIZE(resp_elems));

    return ret;
}
