/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2021 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "json/neu_json_add_tag.h"

int neu_parse_decode_add_tags_req(char *buf, neu_parse_add_tags_req_t **result)
{
    int ret = 0;

    neu_parse_add_tags_req_t *req = calloc(1, sizeof(neu_parse_add_tags_req_t));
    neu_json_elem_t           req_elems[] = { {
                                        .name = "node_id",
                                        .t    = NEU_JSON_INT,
                                    },
                                    {
                                        .name = "group_config_name",
                                        .t    = NEU_JSON_STR,
                                    } };
    ret = neu_json_decode(buf, NEU_JSON_ELEM_SIZE(req_elems), req_elems);
    if (ret != 0) {
        goto decode_fail;
    }

    req->node_id           = req_elems[0].v.val_int;
    req->group_config_name = req_elems[1].v.val_str;

    req->n_tag = neu_json_decode_array_size(buf, "tags");
    req->tags  = calloc(req->n_tag, sizeof(neu_parse_add_tags_req_tag_t));
    neu_parse_add_tags_req_tag_t *p_tag = req->tags;
    for (int i = 0; i < req->n_tag; i++) {
        neu_json_elem_t tag_elems[] = { {
                                            .name = "type",
                                            .t    = NEU_JSON_INT,
                                        },
                                        {
                                            .name = "name",
                                            .t    = NEU_JSON_STR,
                                        },
                                        {
                                            .name = "attribute",
                                            .t    = NEU_JSON_INT,
                                        },
                                        {
                                            .name = "address",
                                            .t    = NEU_JSON_STR,
                                        } };
        ret                         = neu_json_decode_array(buf, "tags", i,
                                    NEU_JSON_ELEM_SIZE(tag_elems), tag_elems);
        if (ret != 0) {
            goto decode_fail;
        }

        p_tag->type      = tag_elems[0].v.val_int;
        p_tag->name      = tag_elems[1].v.val_str;
        p_tag->attribute = tag_elems[2].v.val_int;
        p_tag->address   = tag_elems[3].v.val_str;
        p_tag++;
    }

    *result = req;
    return ret;

decode_fail:
    if (req->tags != NULL) {
        free(req->tags);
    }
    if (req != NULL) {
        free(req);
    }
    return -1;
}

void neu_parse_decode_add_tags_req_free(neu_parse_add_tags_req_t *req)
{

    neu_parse_add_tags_req_tag_t *p_tag = req->tags;
    for (int i = 0; i < req->n_tag; i++) {
        free(p_tag->name);
        free(p_tag->address);
        p_tag++;
    }

    free(req->tags);
    free(req->group_config_name);

    free(req);
}
