/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2022 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "neu_json_file.h"

int neu_json_encode_get_file_list_resp(void *json_object, void *param)
{
    int                            ret = 0;
    neu_json_get_file_list_resp_t *resp =
        (neu_json_get_file_list_resp_t *) param;

    void *                    file_list_array = neu_json_array();
    neu_json_get_file_resp_t *p_file          = resp->file;

    for (int i = 0; i < resp->n_file; i++) {
        neu_json_elem_t file_elems[] = {
            {
                .name      = "name",
                .t         = NEU_JSON_STR,
                .v.val_str = p_file->name,
            },
            {
                .name      = "size",
                .t         = NEU_JSON_INT,
                .v.val_int = p_file->size,
            },
            {
                .name      = "ctime",
                .t         = NEU_JSON_STR,
                .v.val_str = p_file->ctime,
            },
            {
                .name      = "mtime",
                .t         = NEU_JSON_STR,
                .v.val_str = p_file->mtime,
            },
        };

        file_list_array = neu_json_encode_array(file_list_array, file_elems,
                                                NEU_JSON_ELEM_SIZE(file_elems));

        p_file++;
    }

    neu_json_elem_t resp_elems[] = { {
        .name         = "files",
        .t            = NEU_JSON_OBJECT,
        .v.val_object = file_list_array,
    } };

    ret = neu_json_encode_field(json_object, resp_elems,
                                NEU_JSON_ELEM_SIZE(resp_elems));

    return ret;
}