/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2022 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "json/neu_json_error.h"

/**
 * 编码错误响应到JSON
 *
 * @param json_object JSON对象指针
 * @param param 要编码的neu_json_error_resp_t结构体指针
 * @return 成功返回0，失败返回非0
 */
int neu_json_encode_error_resp(void *json_object, void *param)
{
    int                    ret  = 0;
    neu_json_error_resp_t *resp = (neu_json_error_resp_t *) param;

    neu_json_elem_t resp_elems[] = { {
        .name      = "error",
        .t         = NEU_JSON_INT,
        .v.val_int = resp->error,
    } };
    ret = neu_json_encode_field(json_object, resp_elems,
                                NEU_JSON_ELEM_SIZE(resp_elems));

    return ret;
}
