/**
 * NEURON IIoT System for Industry 4.0
 * Copyright (C) 2020-2021 EMQ Technologies Co., Ltd All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 **/

/*
 * DO NOT EDIT THIS FILE MANUALLY!
 * It was automatically generated by `json-autotype`.
 */

#include <stdlib.h>
#include <string.h>

#include "json/json.h"

#include "json/neu_json_get_tag.h"

int neu_parse_decode_get_tags_req(char *buf, neu_parse_get_tags_req_t **result)
{
    int ret = 0;

    neu_parse_get_tags_req_t *req = calloc(1, sizeof(neu_parse_get_tags_req_t));
    neu_json_elem_t           req_elems[] = { {
                                        .name = "node_id",
                                        .t    = NEU_JSON_INT,
                                    },
                                    {
                                        .name = "group_config_name",
                                        .t    = NEU_JSON_STR,
                                    } };
    ret = neu_json_decode(buf, NEU_JSON_ELEM_SIZE(req_elems), req_elems);
    if (ret != 0) {
        goto decode_fail;
    }

    req->node_id           = req_elems[0].v.val_int;
    req->group_config_name = req_elems[1].v.val_str;

    *result = req;
    return ret;

decode_fail:
    if (req != NULL) {
        free(req);
    }
    return -1;
}

void neu_parse_decode_get_tags_req_free(neu_parse_get_tags_req_t *req)
{

    free(req->group_config_name);

    free(req);
}

int neu_parse_encode_get_tags_resp(void *json_object, void *param)
{
    int                        ret  = 0;
    neu_parse_get_tags_resp_t *resp = (neu_parse_get_tags_resp_t *) param;

    void *                         tag_array = NULL;
    neu_parse_get_tags_resp_tag_t *p_tag     = resp->tags;
    for (int i = 0; i < resp->n_tag; i++) {
        neu_json_elem_t tag_elems[] = { {
                                            .name      = "type",
                                            .t         = NEU_JSON_INT,
                                            .v.val_int = p_tag->type,
                                        },
                                        {
                                            .name      = "name",
                                            .t         = NEU_JSON_STR,
                                            .v.val_str = p_tag->name,
                                        },
                                        {
                                            .name      = "id",
                                            .t         = NEU_JSON_INT,
                                            .v.val_int = p_tag->id,
                                        },
                                        {
                                            .name = "group_config_name",
                                            .t    = NEU_JSON_STR,
                                            .v.val_str =
                                                p_tag->group_config_name,
                                        },
                                        {
                                            .name      = "attribute",
                                            .t         = NEU_JSON_INT,
                                            .v.val_int = p_tag->attribute,
                                        },
                                        {
                                            .name      = "address",
                                            .t         = NEU_JSON_STR,
                                            .v.val_str = p_tag->address,
                                        } };
        tag_array = neu_json_encode_array(tag_array, tag_elems,
                                          NEU_JSON_ELEM_SIZE(tag_elems));
        p_tag++;
    }

    neu_json_elem_t resp_elems[] = { {
        .name         = "tags",
        .t            = NEU_JSON_OBJECT,
        .v.val_object = tag_array,
    } };
    ret = neu_json_encode_field(json_object, resp_elems,
                                NEU_JSON_ELEM_SIZE(resp_elems));

    return ret;
}
