/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ptformat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ptformat.pb-c.h"
void   model__driver_action_request__init
                     (Model__DriverActionRequest         *message)
{
  static const Model__DriverActionRequest init_value = MODEL__DRIVER_ACTION_REQUEST__INIT;
  *message = init_value;
}
size_t model__driver_action_request__get_packed_size
                     (const Model__DriverActionRequest *message)
{
  assert(message->base.descriptor == &model__driver_action_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__driver_action_request__pack
                     (const Model__DriverActionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__driver_action_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__driver_action_request__pack_to_buffer
                     (const Model__DriverActionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__driver_action_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__DriverActionRequest *
       model__driver_action_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__DriverActionRequest *)
     protobuf_c_message_unpack (&model__driver_action_request__descriptor,
                                allocator, len, data);
}
void   model__driver_action_request__free_unpacked
                     (Model__DriverActionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__driver_action_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__driver_action_response__init
                     (Model__DriverActionResponse         *message)
{
  static const Model__DriverActionResponse init_value = MODEL__DRIVER_ACTION_RESPONSE__INIT;
  *message = init_value;
}
size_t model__driver_action_response__get_packed_size
                     (const Model__DriverActionResponse *message)
{
  assert(message->base.descriptor == &model__driver_action_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__driver_action_response__pack
                     (const Model__DriverActionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__driver_action_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__driver_action_response__pack_to_buffer
                     (const Model__DriverActionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__driver_action_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__DriverActionResponse *
       model__driver_action_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__DriverActionResponse *)
     protobuf_c_message_unpack (&model__driver_action_response__descriptor,
                                allocator, len, data);
}
void   model__driver_action_response__free_unpacked
                     (Model__DriverActionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__driver_action_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__data_item_value__init
                     (Model__DataItemValue         *message)
{
  static const Model__DataItemValue init_value = MODEL__DATA_ITEM_VALUE__INIT;
  *message = init_value;
}
size_t model__data_item_value__get_packed_size
                     (const Model__DataItemValue *message)
{
  assert(message->base.descriptor == &model__data_item_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__data_item_value__pack
                     (const Model__DataItemValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__data_item_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__data_item_value__pack_to_buffer
                     (const Model__DataItemValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__data_item_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__DataItemValue *
       model__data_item_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__DataItemValue *)
     protobuf_c_message_unpack (&model__data_item_value__descriptor,
                                allocator, len, data);
}
void   model__data_item_value__free_unpacked
                     (Model__DataItemValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__data_item_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__data_item__init
                     (Model__DataItem         *message)
{
  static const Model__DataItem init_value = MODEL__DATA_ITEM__INIT;
  *message = init_value;
}
size_t model__data_item__get_packed_size
                     (const Model__DataItem *message)
{
  assert(message->base.descriptor == &model__data_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__data_item__pack
                     (const Model__DataItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__data_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__data_item__pack_to_buffer
                     (const Model__DataItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__data_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__DataItem *
       model__data_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__DataItem *)
     protobuf_c_message_unpack (&model__data_item__descriptor,
                                allocator, len, data);
}
void   model__data_item__free_unpacked
                     (Model__DataItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__data_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__data_report__init
                     (Model__DataReport         *message)
{
  static const Model__DataReport init_value = MODEL__DATA_REPORT__INIT;
  *message = init_value;
}
size_t model__data_report__get_packed_size
                     (const Model__DataReport *message)
{
  assert(message->base.descriptor == &model__data_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__data_report__pack
                     (const Model__DataReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__data_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__data_report__pack_to_buffer
                     (const Model__DataReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__data_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__DataReport *
       model__data_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__DataReport *)
     protobuf_c_message_unpack (&model__data_report__descriptor,
                                allocator, len, data);
}
void   model__data_report__free_unpacked
                     (Model__DataReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__data_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__read_request__init
                     (Model__ReadRequest         *message)
{
  static const Model__ReadRequest init_value = MODEL__READ_REQUEST__INIT;
  *message = init_value;
}
size_t model__read_request__get_packed_size
                     (const Model__ReadRequest *message)
{
  assert(message->base.descriptor == &model__read_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__read_request__pack
                     (const Model__ReadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__read_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__read_request__pack_to_buffer
                     (const Model__ReadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__read_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__ReadRequest *
       model__read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__ReadRequest *)
     protobuf_c_message_unpack (&model__read_request__descriptor,
                                allocator, len, data);
}
void   model__read_request__free_unpacked
                     (Model__ReadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__read_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__read_response__init
                     (Model__ReadResponse         *message)
{
  static const Model__ReadResponse init_value = MODEL__READ_RESPONSE__INIT;
  *message = init_value;
}
size_t model__read_response__get_packed_size
                     (const Model__ReadResponse *message)
{
  assert(message->base.descriptor == &model__read_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__read_response__pack
                     (const Model__ReadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__read_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__read_response__pack_to_buffer
                     (const Model__ReadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__read_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__ReadResponse *
       model__read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__ReadResponse *)
     protobuf_c_message_unpack (&model__read_response__descriptor,
                                allocator, len, data);
}
void   model__read_response__free_unpacked
                     (Model__ReadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__read_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__write_request__init
                     (Model__WriteRequest         *message)
{
  static const Model__WriteRequest init_value = MODEL__WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t model__write_request__get_packed_size
                     (const Model__WriteRequest *message)
{
  assert(message->base.descriptor == &model__write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__write_request__pack
                     (const Model__WriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__write_request__pack_to_buffer
                     (const Model__WriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__WriteRequest *
       model__write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__WriteRequest *)
     protobuf_c_message_unpack (&model__write_request__descriptor,
                                allocator, len, data);
}
void   model__write_request__free_unpacked
                     (Model__WriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__write_response_item__init
                     (Model__WriteResponseItem         *message)
{
  static const Model__WriteResponseItem init_value = MODEL__WRITE_RESPONSE_ITEM__INIT;
  *message = init_value;
}
size_t model__write_response_item__get_packed_size
                     (const Model__WriteResponseItem *message)
{
  assert(message->base.descriptor == &model__write_response_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__write_response_item__pack
                     (const Model__WriteResponseItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__write_response_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__write_response_item__pack_to_buffer
                     (const Model__WriteResponseItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__write_response_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__WriteResponseItem *
       model__write_response_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__WriteResponseItem *)
     protobuf_c_message_unpack (&model__write_response_item__descriptor,
                                allocator, len, data);
}
void   model__write_response_item__free_unpacked
                     (Model__WriteResponseItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__write_response_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__write_response__init
                     (Model__WriteResponse         *message)
{
  static const Model__WriteResponse init_value = MODEL__WRITE_RESPONSE__INIT;
  *message = init_value;
}
size_t model__write_response__get_packed_size
                     (const Model__WriteResponse *message)
{
  assert(message->base.descriptor == &model__write_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__write_response__pack
                     (const Model__WriteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__write_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__write_response__pack_to_buffer
                     (const Model__WriteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__write_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__WriteResponse *
       model__write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__WriteResponse *)
     protobuf_c_message_unpack (&model__write_response__descriptor,
                                allocator, len, data);
}
void   model__write_response__free_unpacked
                     (Model__WriteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__write_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__node_state_report__init
                     (Model__NodeStateReport         *message)
{
  static const Model__NodeStateReport init_value = MODEL__NODE_STATE_REPORT__INIT;
  *message = init_value;
}
size_t model__node_state_report__get_packed_size
                     (const Model__NodeStateReport *message)
{
  assert(message->base.descriptor == &model__node_state_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__node_state_report__pack
                     (const Model__NodeStateReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__node_state_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__node_state_report__pack_to_buffer
                     (const Model__NodeStateReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__node_state_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__NodeStateReport *
       model__node_state_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__NodeStateReport *)
     protobuf_c_message_unpack (&model__node_state_report__descriptor,
                                allocator, len, data);
}
void   model__node_state_report__free_unpacked
                     (Model__NodeStateReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__node_state_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__node_state__init
                     (Model__NodeState         *message)
{
  static const Model__NodeState init_value = MODEL__NODE_STATE__INIT;
  *message = init_value;
}
size_t model__node_state__get_packed_size
                     (const Model__NodeState *message)
{
  assert(message->base.descriptor == &model__node_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__node_state__pack
                     (const Model__NodeState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__node_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__node_state__pack_to_buffer
                     (const Model__NodeState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__node_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__NodeState *
       model__node_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__NodeState *)
     protobuf_c_message_unpack (&model__node_state__descriptor,
                                allocator, len, data);
}
void   model__node_state__free_unpacked
                     (Model__NodeState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__node_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_list_request__init
                     (Model__FileListRequest         *message)
{
  static const Model__FileListRequest init_value = MODEL__FILE_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t model__file_list_request__get_packed_size
                     (const Model__FileListRequest *message)
{
  assert(message->base.descriptor == &model__file_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_list_request__pack
                     (const Model__FileListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_list_request__pack_to_buffer
                     (const Model__FileListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileListRequest *
       model__file_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileListRequest *)
     protobuf_c_message_unpack (&model__file_list_request__descriptor,
                                allocator, len, data);
}
void   model__file_list_request__free_unpacked
                     (Model__FileListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_list_response__init
                     (Model__FileListResponse         *message)
{
  static const Model__FileListResponse init_value = MODEL__FILE_LIST_RESPONSE__INIT;
  *message = init_value;
}
size_t model__file_list_response__get_packed_size
                     (const Model__FileListResponse *message)
{
  assert(message->base.descriptor == &model__file_list_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_list_response__pack
                     (const Model__FileListResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_list_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_list_response__pack_to_buffer
                     (const Model__FileListResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_list_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileListResponse *
       model__file_list_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileListResponse *)
     protobuf_c_message_unpack (&model__file_list_response__descriptor,
                                allocator, len, data);
}
void   model__file_list_response__free_unpacked
                     (Model__FileListResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_list_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_item__init
                     (Model__FileItem         *message)
{
  static const Model__FileItem init_value = MODEL__FILE_ITEM__INIT;
  *message = init_value;
}
size_t model__file_item__get_packed_size
                     (const Model__FileItem *message)
{
  assert(message->base.descriptor == &model__file_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_item__pack
                     (const Model__FileItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_item__pack_to_buffer
                     (const Model__FileItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileItem *
       model__file_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileItem *)
     protobuf_c_message_unpack (&model__file_item__descriptor,
                                allocator, len, data);
}
void   model__file_item__free_unpacked
                     (Model__FileItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_upload_request__init
                     (Model__FileUploadRequest         *message)
{
  static const Model__FileUploadRequest init_value = MODEL__FILE_UPLOAD_REQUEST__INIT;
  *message = init_value;
}
size_t model__file_upload_request__get_packed_size
                     (const Model__FileUploadRequest *message)
{
  assert(message->base.descriptor == &model__file_upload_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_upload_request__pack
                     (const Model__FileUploadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_upload_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_upload_request__pack_to_buffer
                     (const Model__FileUploadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_upload_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileUploadRequest *
       model__file_upload_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileUploadRequest *)
     protobuf_c_message_unpack (&model__file_upload_request__descriptor,
                                allocator, len, data);
}
void   model__file_upload_request__free_unpacked
                     (Model__FileUploadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_upload_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_upload_response__init
                     (Model__FileUploadResponse         *message)
{
  static const Model__FileUploadResponse init_value = MODEL__FILE_UPLOAD_RESPONSE__INIT;
  *message = init_value;
}
size_t model__file_upload_response__get_packed_size
                     (const Model__FileUploadResponse *message)
{
  assert(message->base.descriptor == &model__file_upload_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_upload_response__pack
                     (const Model__FileUploadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_upload_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_upload_response__pack_to_buffer
                     (const Model__FileUploadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_upload_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileUploadResponse *
       model__file_upload_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileUploadResponse *)
     protobuf_c_message_unpack (&model__file_upload_response__descriptor,
                                allocator, len, data);
}
void   model__file_upload_response__free_unpacked
                     (Model__FileUploadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_upload_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_upload_data_request__init
                     (Model__FileUploadDataRequest         *message)
{
  static const Model__FileUploadDataRequest init_value = MODEL__FILE_UPLOAD_DATA_REQUEST__INIT;
  *message = init_value;
}
size_t model__file_upload_data_request__get_packed_size
                     (const Model__FileUploadDataRequest *message)
{
  assert(message->base.descriptor == &model__file_upload_data_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_upload_data_request__pack
                     (const Model__FileUploadDataRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_upload_data_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_upload_data_request__pack_to_buffer
                     (const Model__FileUploadDataRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_upload_data_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileUploadDataRequest *
       model__file_upload_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileUploadDataRequest *)
     protobuf_c_message_unpack (&model__file_upload_data_request__descriptor,
                                allocator, len, data);
}
void   model__file_upload_data_request__free_unpacked
                     (Model__FileUploadDataRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_upload_data_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_upload_data_response__init
                     (Model__FileUploadDataResponse         *message)
{
  static const Model__FileUploadDataResponse init_value = MODEL__FILE_UPLOAD_DATA_RESPONSE__INIT;
  *message = init_value;
}
size_t model__file_upload_data_response__get_packed_size
                     (const Model__FileUploadDataResponse *message)
{
  assert(message->base.descriptor == &model__file_upload_data_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_upload_data_response__pack
                     (const Model__FileUploadDataResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_upload_data_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_upload_data_response__pack_to_buffer
                     (const Model__FileUploadDataResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_upload_data_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileUploadDataResponse *
       model__file_upload_data_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileUploadDataResponse *)
     protobuf_c_message_unpack (&model__file_upload_data_response__descriptor,
                                allocator, len, data);
}
void   model__file_upload_data_response__free_unpacked
                     (Model__FileUploadDataResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_upload_data_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_download_request__init
                     (Model__FileDownloadRequest         *message)
{
  static const Model__FileDownloadRequest init_value = MODEL__FILE_DOWNLOAD_REQUEST__INIT;
  *message = init_value;
}
size_t model__file_download_request__get_packed_size
                     (const Model__FileDownloadRequest *message)
{
  assert(message->base.descriptor == &model__file_download_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_download_request__pack
                     (const Model__FileDownloadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_download_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_download_request__pack_to_buffer
                     (const Model__FileDownloadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_download_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileDownloadRequest *
       model__file_download_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileDownloadRequest *)
     protobuf_c_message_unpack (&model__file_download_request__descriptor,
                                allocator, len, data);
}
void   model__file_download_request__free_unpacked
                     (Model__FileDownloadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_download_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_download_response__init
                     (Model__FileDownloadResponse         *message)
{
  static const Model__FileDownloadResponse init_value = MODEL__FILE_DOWNLOAD_RESPONSE__INIT;
  *message = init_value;
}
size_t model__file_download_response__get_packed_size
                     (const Model__FileDownloadResponse *message)
{
  assert(message->base.descriptor == &model__file_download_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_download_response__pack
                     (const Model__FileDownloadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_download_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_download_response__pack_to_buffer
                     (const Model__FileDownloadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_download_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileDownloadResponse *
       model__file_download_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileDownloadResponse *)
     protobuf_c_message_unpack (&model__file_download_response__descriptor,
                                allocator, len, data);
}
void   model__file_download_response__free_unpacked
                     (Model__FileDownloadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_download_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_download_data_request__init
                     (Model__FileDownloadDataRequest         *message)
{
  static const Model__FileDownloadDataRequest init_value = MODEL__FILE_DOWNLOAD_DATA_REQUEST__INIT;
  *message = init_value;
}
size_t model__file_download_data_request__get_packed_size
                     (const Model__FileDownloadDataRequest *message)
{
  assert(message->base.descriptor == &model__file_download_data_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_download_data_request__pack
                     (const Model__FileDownloadDataRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_download_data_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_download_data_request__pack_to_buffer
                     (const Model__FileDownloadDataRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_download_data_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileDownloadDataRequest *
       model__file_download_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileDownloadDataRequest *)
     protobuf_c_message_unpack (&model__file_download_data_request__descriptor,
                                allocator, len, data);
}
void   model__file_download_data_request__free_unpacked
                     (Model__FileDownloadDataRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_download_data_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   model__file_download_data_response__init
                     (Model__FileDownloadDataResponse         *message)
{
  static const Model__FileDownloadDataResponse init_value = MODEL__FILE_DOWNLOAD_DATA_RESPONSE__INIT;
  *message = init_value;
}
size_t model__file_download_data_response__get_packed_size
                     (const Model__FileDownloadDataResponse *message)
{
  assert(message->base.descriptor == &model__file_download_data_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t model__file_download_data_response__pack
                     (const Model__FileDownloadDataResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &model__file_download_data_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t model__file_download_data_response__pack_to_buffer
                     (const Model__FileDownloadDataResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &model__file_download_data_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Model__FileDownloadDataResponse *
       model__file_download_data_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Model__FileDownloadDataResponse *)
     protobuf_c_message_unpack (&model__file_download_data_response__descriptor,
                                allocator, len, data);
}
void   model__file_download_data_response__free_unpacked
                     (Model__FileDownloadDataResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &model__file_download_data_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor model__driver_action_request__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DriverActionRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DriverActionRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DriverActionRequest, action),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__driver_action_request__field_indices_by_name[] = {
  2,   /* field[2] = action */
  1,   /* field[1] = node */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__driver_action_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__driver_action_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.DriverActionRequest",
  "DriverActionRequest",
  "Model__DriverActionRequest",
  "model",
  sizeof(Model__DriverActionRequest),
  3,
  model__driver_action_request__field_descriptors,
  model__driver_action_request__field_indices_by_name,
  1,  model__driver_action_request__number_ranges,
  (ProtobufCMessageInit) model__driver_action_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__driver_action_response__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DriverActionResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__DriverActionResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__driver_action_response__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__driver_action_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__driver_action_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.DriverActionResponse",
  "DriverActionResponse",
  "Model__DriverActionResponse",
  "model",
  sizeof(Model__DriverActionResponse),
  2,
  model__driver_action_response__field_descriptors,
  model__driver_action_response__field_indices_by_name,
  1,  model__driver_action_response__number_ranges,
  (ProtobufCMessageInit) model__driver_action_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__data_item_value__field_descriptors[4] =
{
  {
    "int_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Model__DataItemValue, value_case),
    offsetof(Model__DataItemValue, int_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Model__DataItemValue, value_case),
    offsetof(Model__DataItemValue, float_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Model__DataItemValue, value_case),
    offsetof(Model__DataItemValue, string_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Model__DataItemValue, value_case),
    offsetof(Model__DataItemValue, bool_value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__data_item_value__field_indices_by_name[] = {
  3,   /* field[3] = bool_value */
  1,   /* field[1] = float_value */
  0,   /* field[0] = int_value */
  2,   /* field[2] = string_value */
};
static const ProtobufCIntRange model__data_item_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__data_item_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.DataItemValue",
  "DataItemValue",
  "Model__DataItemValue",
  "model",
  sizeof(Model__DataItemValue),
  4,
  model__data_item_value__field_descriptors,
  model__data_item_value__field_indices_by_name,
  1,  model__data_item_value__number_ranges,
  (ProtobufCMessageInit) model__data_item_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__data_item__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DataItem, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__DataItem, item_case),
    offsetof(Model__DataItem, value),
    &model__data_item_value__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Model__DataItem, item_case),
    offsetof(Model__DataItem, error),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Model__DataItem, has_q),
    offsetof(Model__DataItem, q),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Model__DataItem, has_t),
    offsetof(Model__DataItem, t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__data_item__field_indices_by_name[] = {
  2,   /* field[2] = error */
  0,   /* field[0] = name */
  3,   /* field[3] = q */
  4,   /* field[4] = t */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange model__data_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor model__data_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.DataItem",
  "DataItem",
  "Model__DataItem",
  "model",
  sizeof(Model__DataItem),
  5,
  model__data_item__field_descriptors,
  model__data_item__field_indices_by_name,
  1,  model__data_item__number_ranges,
  (ProtobufCMessageInit) model__data_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__data_report__field_descriptors[4] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DataReport, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__DataReport, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Model__DataReport, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__DataReport, n_tags),
    offsetof(Model__DataReport, tags),
    &model__data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__data_report__field_indices_by_name[] = {
  1,   /* field[1] = group */
  0,   /* field[0] = node */
  3,   /* field[3] = tags */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange model__data_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__data_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.DataReport",
  "DataReport",
  "Model__DataReport",
  "model",
  sizeof(Model__DataReport),
  4,
  model__data_report__field_descriptors,
  model__data_report__field_indices_by_name,
  1,  model__data_report__number_ranges,
  (ProtobufCMessageInit) model__data_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__read_request__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__ReadRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__ReadRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__ReadRequest, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Model__ReadRequest, n_tags),
    offsetof(Model__ReadRequest, tags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__read_request__field_indices_by_name[] = {
  2,   /* field[2] = group */
  1,   /* field[1] = node */
  3,   /* field[3] = tags */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__read_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__read_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.ReadRequest",
  "ReadRequest",
  "Model__ReadRequest",
  "model",
  sizeof(Model__ReadRequest),
  4,
  model__read_request__field_descriptors,
  model__read_request__field_indices_by_name,
  1,  model__read_request__number_ranges,
  (ProtobufCMessageInit) model__read_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__read_response__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__ReadResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__ReadResponse, n_tags),
    offsetof(Model__ReadResponse, tags),
    &model__data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__read_response__field_indices_by_name[] = {
  1,   /* field[1] = tags */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__read_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__read_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.ReadResponse",
  "ReadResponse",
  "Model__ReadResponse",
  "model",
  sizeof(Model__ReadResponse),
  2,
  model__read_response__field_descriptors,
  model__read_response__field_indices_by_name,
  1,  model__read_response__number_ranges,
  (ProtobufCMessageInit) model__read_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__write_request__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__WriteRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__WriteRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__WriteRequest, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__WriteRequest, n_tags),
    offsetof(Model__WriteRequest, tags),
    &model__data_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__write_request__field_indices_by_name[] = {
  2,   /* field[2] = group */
  1,   /* field[1] = node */
  3,   /* field[3] = tags */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.WriteRequest",
  "WriteRequest",
  "Model__WriteRequest",
  "model",
  sizeof(Model__WriteRequest),
  4,
  model__write_request__field_descriptors,
  model__write_request__field_indices_by_name,
  1,  model__write_request__number_ranges,
  (ProtobufCMessageInit) model__write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__write_response_item__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__WriteResponseItem, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__WriteResponseItem, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__write_response_item__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange model__write_response_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__write_response_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.WriteResponseItem",
  "WriteResponseItem",
  "Model__WriteResponseItem",
  "model",
  sizeof(Model__WriteResponseItem),
  2,
  model__write_response_item__field_descriptors,
  model__write_response_item__field_indices_by_name,
  1,  model__write_response_item__number_ranges,
  (ProtobufCMessageInit) model__write_response_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__write_response__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__WriteResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errors",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__WriteResponse, n_errors),
    offsetof(Model__WriteResponse, errors),
    &model__write_response_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__write_response__field_indices_by_name[] = {
  1,   /* field[1] = errors */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__write_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__write_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.WriteResponse",
  "WriteResponse",
  "Model__WriteResponse",
  "model",
  sizeof(Model__WriteResponse),
  2,
  model__write_response__field_descriptors,
  model__write_response__field_indices_by_name,
  1,  model__write_response__number_ranges,
  (ProtobufCMessageInit) model__write_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__node_state_report__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Model__NodeStateReport, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__NodeStateReport, n_nodes),
    offsetof(Model__NodeStateReport, nodes),
    &model__node_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__node_state_report__field_indices_by_name[] = {
  1,   /* field[1] = nodes */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange model__node_state_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__node_state_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.NodeStateReport",
  "NodeStateReport",
  "Model__NodeStateReport",
  "model",
  sizeof(Model__NodeStateReport),
  2,
  model__node_state_report__field_descriptors,
  model__node_state_report__field_indices_by_name,
  1,  model__node_state_report__number_ranges,
  (ProtobufCMessageInit) model__node_state_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__node_state__field_descriptors[3] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__NodeState, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__NodeState, link),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "running",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__NodeState, running),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__node_state__field_indices_by_name[] = {
  1,   /* field[1] = link */
  0,   /* field[0] = node */
  2,   /* field[2] = running */
};
static const ProtobufCIntRange model__node_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__node_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.NodeState",
  "NodeState",
  "Model__NodeState",
  "model",
  sizeof(Model__NodeState),
  3,
  model__node_state__field_descriptors,
  model__node_state__field_indices_by_name,
  1,  model__node_state__number_ranges,
  (ProtobufCMessageInit) model__node_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_list_request__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileListRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileListRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileListRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_list_request__field_indices_by_name[] = {
  1,   /* field[1] = node */
  2,   /* field[2] = path */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_list_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__file_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileListRequest",
  "FileListRequest",
  "Model__FileListRequest",
  "model",
  sizeof(Model__FileListRequest),
  3,
  model__file_list_request__field_descriptors,
  model__file_list_request__field_indices_by_name,
  1,  model__file_list_request__number_ranges,
  (ProtobufCMessageInit) model__file_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_list_response__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileListResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileListResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "files",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Model__FileListResponse, n_files),
    offsetof(Model__FileListResponse, files),
    &model__file_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_list_response__field_indices_by_name[] = {
  1,   /* field[1] = error */
  2,   /* field[2] = files */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_list_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__file_list_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileListResponse",
  "FileListResponse",
  "Model__FileListResponse",
  "model",
  sizeof(Model__FileListResponse),
  3,
  model__file_list_response__field_descriptors,
  model__file_list_response__field_indices_by_name,
  1,  model__file_list_response__number_ranges,
  (ProtobufCMessageInit) model__file_list_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_item__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileItem, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileItem, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileItem, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Model__FileItem, t),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_item__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = size */
  3,   /* field[3] = t */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange model__file_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__file_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileItem",
  "FileItem",
  "Model__FileItem",
  "model",
  sizeof(Model__FileItem),
  4,
  model__file_item__field_descriptors,
  model__file_item__field_indices_by_name,
  1,  model__file_item__number_ranges,
  (ProtobufCMessageInit) model__file_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_upload_request__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_upload_request__field_indices_by_name[] = {
  1,   /* field[1] = node */
  2,   /* field[2] = path */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_upload_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__file_upload_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileUploadRequest",
  "FileUploadRequest",
  "Model__FileUploadRequest",
  "model",
  sizeof(Model__FileUploadRequest),
  3,
  model__file_upload_request__field_descriptors,
  model__file_upload_request__field_indices_by_name,
  1,  model__file_upload_request__number_ranges,
  (ProtobufCMessageInit) model__file_upload_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_upload_response__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_upload_response__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_upload_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__file_upload_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileUploadResponse",
  "FileUploadResponse",
  "Model__FileUploadResponse",
  "model",
  sizeof(Model__FileUploadResponse),
  2,
  model__file_upload_response__field_descriptors,
  model__file_upload_response__field_indices_by_name,
  1,  model__file_upload_response__number_ranges,
  (ProtobufCMessageInit) model__file_upload_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_upload_data_request__field_descriptors[3] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_upload_data_request__field_indices_by_name[] = {
  1,   /* field[1] = node */
  2,   /* field[2] = path */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_upload_data_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor model__file_upload_data_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileUploadDataRequest",
  "FileUploadDataRequest",
  "Model__FileUploadDataRequest",
  "model",
  sizeof(Model__FileUploadDataRequest),
  3,
  model__file_upload_data_request__field_descriptors,
  model__file_upload_data_request__field_indices_by_name,
  1,  model__file_upload_data_request__number_ranges,
  (ProtobufCMessageInit) model__file_upload_data_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_upload_data_response__field_descriptors[4] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "more",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataResponse, more),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileUploadDataResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_upload_data_response__field_indices_by_name[] = {
  2,   /* field[2] = data */
  3,   /* field[3] = error */
  1,   /* field[1] = more */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_upload_data_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__file_upload_data_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileUploadDataResponse",
  "FileUploadDataResponse",
  "Model__FileUploadDataResponse",
  "model",
  sizeof(Model__FileUploadDataResponse),
  4,
  model__file_upload_data_response__field_descriptors,
  model__file_upload_data_response__field_indices_by_name,
  1,  model__file_upload_data_response__number_ranges,
  (ProtobufCMessageInit) model__file_upload_data_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_download_request__field_descriptors[5] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadRequest, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_path",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadRequest, src_path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_path",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadRequest, dst_path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_download_request__field_indices_by_name[] = {
  3,   /* field[3] = dst_path */
  1,   /* field[1] = node */
  4,   /* field[4] = size */
  2,   /* field[2] = src_path */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_download_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor model__file_download_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileDownloadRequest",
  "FileDownloadRequest",
  "Model__FileDownloadRequest",
  "model",
  sizeof(Model__FileDownloadRequest),
  5,
  model__file_download_request__field_descriptors,
  model__file_download_request__field_indices_by_name,
  1,  model__file_download_request__number_ranges,
  (ProtobufCMessageInit) model__file_download_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_download_response__field_descriptors[2] =
{
  {
    "uuid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadResponse, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_download_response__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = uuid */
};
static const ProtobufCIntRange model__file_download_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__file_download_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileDownloadResponse",
  "FileDownloadResponse",
  "Model__FileDownloadResponse",
  "model",
  sizeof(Model__FileDownloadResponse),
  2,
  model__file_download_response__field_descriptors,
  model__file_download_response__field_indices_by_name,
  1,  model__file_download_response__number_ranges,
  (ProtobufCMessageInit) model__file_download_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_download_data_request__field_descriptors[2] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataRequest, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataRequest, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_download_data_request__field_indices_by_name[] = {
  0,   /* field[0] = node */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange model__file_download_data_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor model__file_download_data_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileDownloadDataRequest",
  "FileDownloadDataRequest",
  "Model__FileDownloadDataRequest",
  "model",
  sizeof(Model__FileDownloadDataRequest),
  2,
  model__file_download_data_request__field_descriptors,
  model__file_download_data_request__field_indices_by_name,
  1,  model__file_download_data_request__number_ranges,
  (ProtobufCMessageInit) model__file_download_data_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor model__file_download_data_response__field_descriptors[4] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataResponse, node),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataResponse, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "more",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataResponse, more),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Model__FileDownloadDataResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned model__file_download_data_response__field_indices_by_name[] = {
  3,   /* field[3] = data */
  2,   /* field[2] = more */
  0,   /* field[0] = node */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange model__file_download_data_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor model__file_download_data_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "model.FileDownloadDataResponse",
  "FileDownloadDataResponse",
  "Model__FileDownloadDataResponse",
  "model",
  sizeof(Model__FileDownloadDataResponse),
  4,
  model__file_download_data_response__field_descriptors,
  model__file_download_data_response__field_indices_by_name,
  1,  model__file_download_data_response__number_ranges,
  (ProtobufCMessageInit) model__file_download_data_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
