name: EMQX Neuron dev workflow

on:
  push:
  pull_request:

jobs:
  clang_format_check:
    runs-on: ubuntu-20.04

    steps:
      # checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run clang-format style check for C/C++ programs.
        uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: 'src plugins include tests'
          exclude: 'include/vector.h'
          clangFormatVersion: 10
          style: file

  compile_x86_64:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        name: [ release ]
        system:
        - [gcc-7, x86_64]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile
        run: |
          git submodule update --init --remote
          sudo apt install -y cmake ninja-build libgtest-dev libssl-dev
          sudo ./install-libs.sh -a
          mkdir build && cd build && cmake .. && make

      - name: Run unit test
        run: cd build && ctest --output-on-failure
