name: EMQX Neuron release workflow

on:
  push:
  release:
    types:
      - published

jobs:
  compile:
    strategy:
      matrix:
        tool:
          - arm-linux-gnueabihf
          - aarch64-linux-gnu

    runs-on: ubuntu-18.04

    container: ghcr.io/${{ github.repository }}/base:latest

    steps:
      # checkout
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile
        working-directory: build
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/${{ matrix.tool }}.cmake
          make

      - name: Run unit test
        working-directory: build
        run: ctest --output-on-failure
